export const UGANDA_DISTRICTS = [
  { name: "Kampala", region: "Central" },
  { name: "Wakiso", region: "Central" },
  { name: "Mukono", region: "Central" },
  { name: "Mpigi", region: "Central" },
  { name: "Luwero", region: "Central" },
  { name: "Masaka", region: "Central" },
  { name: "Rakai", region: "Central" },
  { name: "Kalangala", region: "Central" },
  { name: "Butambala", region: "Central" },
  { name: "Gomba", region: "Central" },
  { name: "Kalungu", region: "Central" },
  { name: "Lyantonde", region: "Central" },
  { name: "Lwengo", region: "Central" },
  { name: "Mityana", region: "Central" },
  { name: "Mubende", region: "Central" },
  { name: "Kassanda", region: "Central" },
  { name: "Kyankwanzi", region: "Central" },
  { name: "Nakaseke", region: "Central" },
  { name: "Nakasongola", region: "Central" },
  { name: "Sembabule", region: "Central" },
  
  { name: "Jinja", region: "Eastern" },
  { name: "Iganga", region: "Eastern" },
  { name: "Kamuli", region: "Eastern" },
  { name: "Mayuge", region: "Eastern" },
  { name: "Mbale", region: "Eastern" },
  { name: "Pallisa", region: "Eastern" },
  { name: "Budaka", region: "Eastern" },
  { name: "Sironko", region: "Eastern" },
  { name: "Manafwa", region: "Eastern" },
  { name: "Tororo", region: "Eastern" },
  { name: "Busia", region: "Eastern" },
  { name: "Bugiri", region: "Eastern" },
  { name: "Namutumba", region: "Eastern" },
  { name: "Butaleja", region: "Eastern" },
  { name: "Kaliro", region: "Eastern" },
  { name: "Buyende", region: "Eastern" },
  { name: "Luuka", region: "Eastern" },
  { name: "Soroti", region: "Eastern" },
  { name: "Serere", region: "Eastern" },
  { name: "Katakwi", region: "Eastern" },
  { name: "Amuria", region: "Eastern" },
  { name: "Kaberamaido", region: "Eastern" },
  { name: "Kumi", region: "Eastern" },
  { name: "Bukedea", region: "Eastern" },
  { name: "Kween", region: "Eastern" },
  { name: "Kapchorwa", region: "Eastern" },
  { name: "Bukwo", region: "Eastern" },
  { name: "Amudat", region: "Eastern" },
  { name: "Nakapiripirit", region: "Eastern" },
  { name: "Moroto", region: "Eastern" },
  { name: "Napak", region: "Eastern" },
  { name: "Kotido", region: "Eastern" },
  { name: "Kaabong", region: "Eastern" },
  { name: "Abim", region: "Eastern" },
  
  { name: "Gulu", region: "Northern" },
  { name: "Kitgum", region: "Northern" },
  { name: "Pader", region: "Northern" },
  { name: "Agago", region: "Northern" },
  { name: "Lamwo", region: "Northern" },
  { name: "Amuru", region: "Northern" },
  { name: "Nwoya", region: "Northern" },
  { name: "Omoro", region: "Northern" },
  { name: "Lira", region: "Northern" },
  { name: "Oyam", region: "Northern" },
  { name: "Otuke", region: "Northern" },
  { name: "Alebtong", region: "Northern" },
  { name: "Dokolo", region: "Northern" },
  { name: "Amolatar", region: "Northern" },
  { name: "Apac", region: "Northern" },
  { name: "Kole", region: "Northern" },
  { name: "Kwania", region: "Northern" },
  
  { name: "Mbarara", region: "Western" },
  { name: "Bushenyi", region: "Western" },
  { name: "Ntungamo", region: "Western" },
  { name: "Mitooma", region: "Western" },
  { name: "Sheema", region: "Western" },
  { name: "Buhweju", region: "Western" },
  { name: "Rubirizi", region: "Western" },
  { name: "Rukungiri", region: "Western" },
  { name: "Kanungu", region: "Western" },
  { name: "Kisoro", region: "Western" },
  { name: "Kabale", region: "Western" },
  { name: "Rubanda", region: "Western" },
  { name: "Ibanda", region: "Western" },
  { name: "Isingiro", region: "Western" },
  { name: "Kiruhura", region: "Western" },
  { name: "Kasese", region: "Western" },
  { name: "Kabarole", region: "Western" },
  { name: "Kamwenge", region: "Western" },
  { name: "Kyenjojo", region: "Western" },
  { name: "Kyegegwa", region: "Western" },
  { name: "Bundibugyo", region: "Western" },
  { name: "Ntoroko", region: "Western" },
  { name: "Hoima", region: "Western" },
  { name: "Masindi", region: "Western" },
  { name: "Kiryandongo", region: "Western" },
  { name: "Buliisa", region: "Western" },
  { name: "Kibaale", region: "Western" },
  { name: "Kakumiro", region: "Western" },
  { name: "Kagadi", region: "Western" },
];

export const SERVICE_TYPES = [
  "Full-time Care",
  "Part-time Care",
  "Night Care",
  "Babysitting",
  "Educational Support",
  "Special Needs Care",
  "Infant Care",
  "Toddler Care",
  "After School Care",
  "Holiday Care",
  "Emergency Care",
  "Live-in Care",
  "Housekeeping",
  "Cooking",
  "Transportation",
];

export const AGE_GROUPS = [
  "0-1 years (Infants)",
  "1-3 years (Toddlers)",
  "3-5 years (Preschool)",
  "5-8 years (Primary)",
  "8-12 years (Middle)",
  "12+ years (Teenagers)",
];

export const AVAILABILITY_OPTIONS = [
  "Weekdays",
  "Weekends",
  "Monday-Friday 9-5",
  "Monday-Friday 8-6",
  "Flexible Hours",
  "Morning Shifts",
  "Evening Shifts",
  "Night Shifts",
  "24/7 Available",
  "On-call",
];

export const LANGUAGES = [
  "English",
  "Luganda",
  "Runyankore",
  "Rukiga",
  "Luo",
  "Ateso",
  "Lugisu",
  "Runyoro",
  "Rutoro",
  "Acholi",
  "Langi",
  "Alur",
  "Lugbara",
  "Swahili",
];
